### ISSUE TITLE
Wont play well on 32bit machines with values >2^32

### ISSUE THREAD

**Issue by PeterSommerlad** [rhalbersma/xstd#18]
From LWG in Albuquerque:

5'000'000'000zu
On a 32bit machine should be a compile error.

**Comment by rhalbersma** [comment]
Thanks Peter, I read the notes on the Wiki. If this behavior is required *at compile-time*, then it should come from a `template<char...> size_t operator "" zu()`, rather than the currently proposed `size_t operator "" zu(unsigned long long)`. Is that what you had in mind as well? 

It's doable, but parsing the various digits and decimal separators makes the implementation cumbersome. I think a language extension (as per the rest of LWG feedback) might be worth consideration in that case.

**Comment by PeterSommerlad** [comment]
The latter is actually what was suggested by LWG for more than the silent overflow problem in your spec. Forcing users to write a using namespace directive makes using that suffix onerous and thus it might not be used. As a language feature such a suffix (i would have preferred the original z ) would not suffer from the overhead in doing so. And size_t is a special type for the compiler anyway. See the lwg wiki notes.

**Comment by rhalbersma** [comment]
The size_t literal proposal was referred LWG as to be in EWG's scope in Albuquerque. I am closing this issue since it would require a separate core language proposal.
